name: taskflow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.4
  csv: ^6.0.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  intl: ^0.19.0
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/monke.gif
    - assets/icon/icon.ico